package com.freed_asd.fuel_calculator.sl

enum class Feature {
    DISTANCE_MAIN,
    DISTANCE_RESULT_DIALOG,
    PRICE_MAIN,
    PRICE_RESULT_DIALOG,
    CONS_MAIN,
    CONS_DISTANCE_BASE,
    CONS_DISTANCE_RESULT,
    CONS_MILEAGE_BASE,
    CONS_MILEAGE_RESULT,
    STATS_TRIPS_BASE,
    STATS_TRIPS_FULL,
    STATS_MILEAGE_TRACK,
    STATS_MILEAGE_CITY,
    STATS_MILEAGE_MIXED
}